### ISSUE TITLE
defaults render cwl invalid

### ISSUE THREAD

**Issue by mwalzer** [WorkflowConversion/CTDConverter#41]
e.g. 
```
the `param_debug` field is not valid because
                               tried int but
                                 `u'0'` is not int
```
which is
```
 - default: '0'
  doc: Sets the debug level
  id: param_debug
  inputBinding:
    prefix: -debug
  label: Sets the debug level
  type:
  - 'null'
  - int
```
So, the defaults type must match (one of?) the cwl param type defined
