### ISSUE TITLE
Flags get not properly translated into cwl

### ISSUE THREAD

**Issue by mwalzer** [WorkflowConversion/CTDConverter#43]
flags (parameters without argument) are placed in the cwl associated with (default)values (of their boolean default values in the tool).

_Originally posted by @mwalzer in https://github.com/WorkflowConversion/CTDConverter/issue_comments#issuecomment-444969252_

**Comment by mwalzer** [comment]
The cwl looks like this:
```
- default: 'false'
  doc: Show meta information about the whole experiment
  id: param_m
  inputBinding:
    prefix: -m
  label: Show meta information about the whole experiment
  type:
  - 'null'
  - string
```
changing to 
```
- doc: Show meta information about the whole experiment
  id: param_m
  inputBinding:
    prefix: -m
  label: Show meta information about the whole experiment
  type:
  - 'null'
```
fixes that, but I am unsure if this is the right cwl way to do it.
